"""Retired static-data entry point.

MarginShield now requires the FastAPI service because scores and the relationship
graph are generated by the app-native coordinated-ring model.
"""

if __name__ == "__main__":
    raise SystemExit("Use build_dataset.py, train_live_model.py, then `python3 -m uvicorn server:app --port 8003`.")
